language: node_js

node_js: stable  # 要安装的node版本为当前的稳定版

cache:
  directories:
  - node_modules # 要缓存的文件夹

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g

after_script:   # 最后执行的命令
  - cd ./public
  - git init
  - git config user.name "sheno-Tyes"
  - git config user.email "lshenu.zhehao@gmail.com"
  - git add . 
  - git commit -m "代码是自动部署的哈"
  - git push --force --quiet "https://${wthzhan}@${GH_REF}" master:gh-pages

branches:
  only:
    - master # 触发持续集成的分支

env:
 global:
   - GH_REF: github.com/sheno-Tyes/wthzhan.git # 就是你github上存放静态博客最终文件 的仓库地址末尾加上.git